### ISSUE TITLE
TODO for future dev

### ISSUE THREAD

**Issue by jGauravGupta** [jeddict/jeddict#118]
**Java EE** 
- [x] H2 DB
- [x] Payara Micro
- [x] Wildfly Swarm
- [ ] Gradle
- [ ] jCache 

**Modeler**
- [ ] DB Modeler native #17 
- [ ] Core UML #24 
- [ ] DTO Modeler #132 
- [x] JSON-B

**Java 8**
- [x] LocalDate and LocalDateTime support

**Comment by Chris2011** [comment]
Possible TODOs, If I'm allowed to post here. If not, then delete or ignore my comment or I will remove it:

- [ ] Please implement: https://github.com/jGauravGupta/JPAModeler/issues/17
- [ ] Please think about this again: https://github.com/jGauravGupta/JPAModeler/issues/24
- [ ] Not so encapsulated with Java EE.
- [ ] Generators for ES6.
- [ ] Generators for TypeScript.

We can discuss those things maybe in other tickets or in a 1 on 1. Atm I know it is more for JavaEE but it has big potential for other Projects which are NOT Java EE. For HTML5/JavaScript or Node too. In combination of Mongo or other DataSources at the backend, REST too and ES6 and TypeScript.

I know this is a lot of work but as you can see easyUML is not really developed further. Yours is great and could be used for more than only Java EE.


Best Regards

Chris

**Comment by jGauravGupta** [comment]
Hi @Chris2011 ,

#17 and #24 are good and will be done in future (right now no strict plan until microservice app generator). 
Angular 2.x release will be available soon so What are you expecting with generators for ES6 & TypeScript ?
Please share the more detail about "**Not so encapsulated with Java EE**".

**Comment by Chris2011** [comment]
Atm you only can create JPA for Java EE projects right? And this will generate Angular1 templates from a such REST and models afaik. It would be good if this is not only possible inside a JavaEE project. It should be possible for a bunch of project types like for HTML5/JavaScript for example. For this you should choose a rest interface/url to got the infos and generator models, for javascript for example and generate Angular1 modules.

The same should be possible for ES6 and for TypeScript. There for we have "classes" with getter and setter. It is now a bit like java nowadays. We have classes inside Es6 and classes, interfaces and manymore for TypeScript. So it should be possible to create such things for HTML5/JavaScript projects and NodeJS (Which is already a HTML5/JavaScript project) too.

Generatore model classes for ES6 and TypeScript NOT only for Java EE Project types and AngularJS1 and AngularJS2 components.

**Comment by jGauravGupta** [comment]
Thanks for sharing the idea, currently JPA Modeler is tightly coupled with
JPA domain/persistence layer and plug-gable with Business layer, Controller
and Viewer layer. So it will take some time to decouple and make the JPA
optional. So that other technology can be plugged with it and contributed
by community.

ATM any one can develop there own generator with JPA Modeler for Business,
Controller and Viewer layer source code as a separate plugin.
e.g : *jpamodeler*.github.io/page.html?l=tutorial/*Contribute*



Thanks and kind regards,
Gaurav Gupta
<https://twitter.com/intent/follow?original_referer=https%3A%2F%2Fabout.twitter.com%2Fresources%2Fbuttons&ref_src=twsrc%5Etfw&region=follow_link&screen_name=jpamodeler&tw_p=followbutton>
<http://jpamodeler.github.io/>   <https://www.youtube.com/JPAModeler>

**Comment by Chris2011** [comment]
Exaactly, it would be good if everything could be optional. JPA Modeler for JavaEE. So you can use it for JavaEE if you need it. DB Modeler, JS Modeler (For example) or DTO Modeler or smth like that. Thx for the info.

**Comment by jGauravGupta** [comment]
For more clarification, first step will be to introduce UML to some extent so that it will be a generic modeling platform then plug-gable domain/persistence layer code generation.

**Comment by Chris2011** [comment]
Yeah UML should be a component which should be independent too. It should be possible to generate code for sure for PHP, Java, JS, etc. But first it should be a modeling tool.

**Comment by Mobidat** [comment]
The natural supplement for the jpa-modeler and db-modeler is a universal view-modeler, where developer are able to assign the Entities configured by the jpa modeler to a abstract visual component (TABLE / FORM / TOOLBAR) . With this relation, it is possible to generate code for MVP structures - independend from the used view framework.

**Comment by slavb18** [comment]
JPA Modeler is greatest modeler tool I have been seen, becouse it is tightly coupled with JPA
A have tried different modeling methods,  including special software, xml and text documents,
but all of them in long run leading  to inconsistency between model and code... Only in JPA modeler I need (and can) to do everything in model, and then generate code, so my model always matches code.

About DTO Modeler... currently i am using xsd schemas to do that, but JPA modeler contains features like "Bean validation Propreties". May be DTO modelling in UI could be useful someday.

**Comment by slavb18** [comment]
JAVA 8    LocalDate and LocalDateTime support - it is already supported, I can  select such classes in Field Type, and use JPA converters. May be UI could contain LocalTime, LocalDate, LocalDateTime in menu in predefined  selectors, to speed up things.

Possible JPA Modeler could also add
    <class>com.github.marschall.threeten.jpa.LocalTimeConverter</class>
    <class>com.github.marschall.threeten.jpa.LocalDateConverter</class>
    <class>com.github.marschall.threeten.jpa.LocalDateTimeConverter</class>
    <class>com.github.marschall.threeten.jpa.LocalDateTimeConverter</class>
to persistance.xml
and pom.xml dependency, but this is almost optional

**Comment by Mobidat** [comment]
A PROPERTY COPY and PASTE function to rearange certain properties between entities would be nice

**Comment by Mobidat** [comment]
There are many other tools to work with entity models  i.e. JHipster, Spring Roo etc.
I think the most common transfer format is XMI-Export file. Is ist possible to generate this with Jeddict? Perhaps there is a hidden feature in Netbeans - I didn't find...

**Comment by jGauravGupta** [comment]
You can create your own extension : https://jeddict.github.io/page.html?l=tutorial/Contribute
Looks like You want to generate Spring code and manage entities with Jeddict.

**Comment by jGauravGupta** [comment]
Hi @Mobidat ,
This extension is much suitable for server/client code generator. Your case is different. So perhaps , if you are interested , I will create extension api for export  :  
![generat1088](https://user-images.githubusercontent.com/15934072/27200961-6d6631a4-5239-11e7-975b-4a7e2caac683.gif)

**Comment by Chris2011** [comment]
So partial UML Support is available too?
